FROM xybersolve/xs-minimal-node-build:latest as builder

ENV SRC_DIR /usr/src

RUN mkdir -p $SRC_DIR
WORKDIR $SRC_DIR

# RUN git clone https://github.com/xybersolve/xybersolve-io.git .
COPY . .

RUN npm install
RUN npm run build:prod

