# Variable Reference
#
# For debugging and notification
# CIRCLE_BUILD_NUM
# CIRCLE_JOB
# CIRCLE_WORKING_DIRECTORY
# CIRCLE_BRANCH 
# CIRCLE_SHA1 
#
# Must be set in CirclCI Context & associated in Workflows
# AWS_ACCESS_KEY_ID
# AWS_SECRET_ACCESS_KEY
# AWS_REGION
#
#
version: 2
jobs:
  #
  #  build: Build Angular app and save to cache  
  #
  build:
    working_directory: ~/xybersolve-build
    
    docker:
      - image: circleci/node:10.12-jessie
    
    steps:
      - checkout
      
      # restore if we have unchanged node mocules 
      - restore-cache:
          keys:
           - v1-dependencies-{{ checksum "package.json" }}
           - v1-dependencies-
      
      # install node modules
      - run: 
          name: Install local dependencies - NPM modules
          command: npm install

      # save node modules 
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      # lint test
      - run:
          name: Lint testing
          command: npm lint 
      
      # unit tests
      - run:
          name: Testing
          command: npm run test
      
      # build for environment
      - run: 
          name: Build app for production
          command: |
            case "${CIRCLE_BRANCH}" in
              develop)
                npm run build:dev
                ;;
              staging)
                npm run build:stage
                ;;
              release)
                npm run build:prod
                ;;
            esac      
      
      # save build artifacts
      # requires: angular.json -> outputPath: dist
      #       or: ng build --prod --output-path=dist
      - save_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - dist

  #          
  # deploy: Deploy angular app from cache to AWS Static S3 Site  
  #          
  deploy:
    docker:
      - image: circleci/python:2.7-jessie
    # - image: circleci/python:3.6.2-stretch-browsers              
    working_directory: ~/xybersolve-build
    
    steps:
      # install AWS Cli
      - run:
          name: Install awscli
          command: sudo pip install awscli
      # Configure AWS Cli 
      - run:
          name: Configure AWS
          command: |
            aws configure set default.s3.signature_version s3v4
            aws configure set region ${AWS_REGION}
            aws configure set aws_access_key_id ${AWS_ACCESS_KEY_ID}
            aws configure set aws_secret_access_key ${AWS_SECRET_ACCESS_KEY}

      # pull build back from cache
      - restore-cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      
      # deploy to S3
      - deploy:
          name: Deploy to S3
          command: |
            case "${CIRCLE_BRANCH}" in
              develop)
                aws s3 sync ./dist s3://xybersolve.io.2/ --delete
                ;;
              staging) 
                aws s3 sync ./dist s3://xybersolve.io.2/ --delete
                ;;
              release)
                aws s3 sync ./dist s3://xybersolve.io/ --delete
                ;;
            esac
            
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          context: xybersolve-io
          filters:
            branches:
              only:
                - release
                - staging
                - develop
                - qa

      - deploy:
          context: xybersolve-io
          requires:
            - build
          filters:
            branches:
              only:
                - release
                - staging
                - develop
                - qa
          
